# Generated by Django 4.2.7 on 2023-11-30 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_lesson_language_alter_lesson_list_of_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='list_of_students',
            field=models.ManyToManyField(related_name='lessons_attended', through='project.Reservation', to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_taught', to='project.usernew'),
        ),
    ]
