# Generated by Django 4.2.7 on 2024-01-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_rename_status_promocode_used_alter_promocode_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
