# Generated by Django 4.2.7 on 2024-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_teacher_user_lesson_name_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('italian', 'Italian'), ('russian', 'Russian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic'), ('slovak', 'Slovak')], max_length=100),
        ),
    ]
