# Generated by Django 4.2.7 on 2023-11-30 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('german', 'German'), ('french', 'French'), ('spanish', 'Spanish'), ('italian', 'Italian'), ('russian', 'Russian'), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabic', 'Arabic')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='list_of_students',
            field=models.ManyToManyField(through='project.Reservation', to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_student', to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_teacher', to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='review',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_as_student', to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='review',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_as_teacher', to='project.usernew'),
        ),
        migrations.AlterField(
            model_name='usernew',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
